#ENC[AES256_GCM,data:H14ggsHYCVF2ZrilyPsv5timAbXeqy3qmhEB/Dkc24ztKnyqlLY6po/wGGLcL6/4KBckk60=,iv:raPcHo3QS+H3y4r1nv7A0wDCi3CgVh9jV3kcsqad3BM=,tag:lrKyXd6IN4bGGV8uluo1Sw==,type:comment]
#ENC[AES256_GCM,data:w8SY2AjSJtZd3j33BhrMpTMmejjLTA3Jfo/gkSxXhOhgvOA=,iv:pzvbYevbKSTEGAuFCEJr1qNA1NaeOvCYZY8iAGGT/zs=,tag:xVxFAbp+Tie5CFuw4NCKKA==,type:comment]
#ENC[AES256_GCM,data:tz4xnjuynRusLA/nNoJoJDGw6Pt/lo2bZj8uoQ==,iv:+7kbkde5J572U3kT4mnLHtwsTEk4PymcaMfRumh0HVY=,tag:66XhWr+tbDiTBpEbLem4jg==,type:comment]
dylan:
    #ENC[AES256_GCM,data:VDi+8U1zTNQ//MJB76LFnEdlSyHGWCQ9cdZcxNYjc2E=,iv:o8C6F8Z7HyeRVUgwdlQflsNHCQ2ag7s4EdtkiOT+Wbs=,tag:c9nm/2ggLESDzRr4xQj7qQ==,type:comment]
    gpg:
        signing_key_id: ENC[AES256_GCM,data:vRmOuV6g2uc1nhPqnPkGaw==,iv:QaSaMuS7CxZ+JCU/YDMTMtTkwcn5cGS8aLf22EiSetQ=,tag:IpeMWss3HW7617ojqXLeqA==,type:str]
        email: ENC[AES256_GCM,data:7FYiHwhgasrTqQlo5dayD68H,iv:vSGLEYClaA9t0FC7+0RiVh4TSWCF+sXD9J8UJSNnNVg=,tag:QwA3KIdzSBVEPo76sN16Cg==,type:str]
        #ENC[AES256_GCM,data:uKl3Z+YHyCDHEJYGpuBHgccd3QIq9j7xdhhmJB09q7OR2EXyMEimu6yn5wPKPJkx7XzhXgfszw7FXCjnBaQE,iv:tTBZkToWUt7ouYBSXHjyd8RXsFQwrRHwGeluAB72mbI=,tag:ttsdaeZ3k4JA0PmDm7PA3g==,type:comment]
        #ENC[AES256_GCM,data:70K5FyEJs5UBuYBt9wSxBdwUvMxUvr0Kd7geq85Z7CW0sWmZvU3X,iv:8qguQwcuDwCF/N5HJforhq5+loVyi0K595Ihz8swO4Y=,tag:EA+3HiNgzXkoBwm9cQe6Ww==,type:comment]
        private_key: ENC[AES256_GCM,data:w11DuTO9CbC2ss0HVfQTMfMYzPGieECinFclHMnRSf4=,iv:f51/kr3UuP2K7RP6oCOVG4SE2GnEpySQPfMFT7w7pVc=,tag:KTWFYaV5ousncrIyu7Vn+g==,type:str]
    #ENC[AES256_GCM,data:XYSImPORFJGTVULNZMUaB+ZPVkvuONgJkpn/hbw=,iv:U5CYfujpRfJdgWMqHNI1LmaE+3CWDZCOIbp1aeHRVus=,tag:0wUdHG+lmMvfQYFpn1iLOA==,type:comment]
    ssh:
        public_key: ENC[AES256_GCM,data:t27kab7W7te+3cUMW5R6fImV9H8YkRA14uAAxGSlVLMnTbB86DvFcS2dXRgIfjvWyE2OYKDzV5i7sJwYQtwY6s9fHKSDoFEnpSEoHPDFsK1r290WbknQWCiIfa21UWifG+r4,iv:kgmquqkqwCoglu7BsX2s/FvExE5CpJT322V358iRdYo=,tag:AKGaP9VGIlYsiQeqmBW06w==,type:str]
        #ENC[AES256_GCM,data:G1AEt9/NVUYBxN/EbsXGt+a77qsHf2gL/xzw/pa6W5zsIMs=,iv:Ep4bYW5XRiss9fqvLlWlInADEGI91CrtFbRbYP7zpPw=,tag:2J6SIJSx4HxJ950qMSOZug==,type:comment]
        #ENC[AES256_GCM,data:86rUQHVlgmkziAda+If7KvkYpEDEZci2Gvmx/n/B98fyS86arpVe,iv:+OZ5EgK5ATDxrRwhw44iH/hM1WxyC/DT0vT6b2fRXDQ=,tag:S+I/Klhv3MrkZuyUGEE49A==,type:comment]
        private_key: ENC[AES256_GCM,data:WCViVMEY4rPrDeNhx0hGw4zO4qD/TrrVeY3CPsXY9yVVCeU=,iv:iUSDN9Pmv4pNrs9XireicsUZOCXmmwSiTXOO85671cQ=,tag:XQl3clVUke4igRl2hjlzUA==,type:str]
    git:
        name: ENC[AES256_GCM,data:iB3BJve9C8K5o2C9gO3w,iv:fA/lgol4E0+/NEWWw4qA4dLlJ8aQmm9tHcyo13HFUgs=,tag:0g15GBwy6r8K5m/gZZRbXQ==,type:str]
        email: ENC[AES256_GCM,data:w9zBi7xW6b6G1mY2NWhdMee8,iv:xNNrSSzaehgTrgJLioCJpfuqRKvn6sTHFmld7hLo6UQ=,tag:NxDdg6O/xzKj1LQfQ+8b0A==,type:str]
#ENC[AES256_GCM,data:c2jvrz6WE5l4QimunC++sluBSU4Jo9CvvhSveexmFoOUJyRg,iv:zX0ZJOn52pxM32reu72Ay8XLCyCDCStbpxz+oGtjh60=,tag:5jKDYYvaM5Ik5tIz8clCJw==,type:comment]
nuck:
    network:
        tailscale_ip: ENC[AES256_GCM,data:XDIe/2akzUOj6Iz7vw==,iv:Uj0DqQ+QNQPFK+0nhUKNH3LHUUUqplZCeJ8tCJJN8No=,tag:4Nt6U3Gb4aTSMiQIQQMVkg==,type:str]
        domain: ENC[AES256_GCM,data:Xul8/8cddQ==,iv:Yt/QuesKCdo/XOkzJc+JEFiMVNLF+7G5c2c7wgfASgM=,tag:TFeUdaqAv5ZbEJiN+kCGew==,type:str]
        hostname: ENC[AES256_GCM,data:zCiQaA==,iv:jImMcntyxhH/58N8TMzTVSG2ip984g13fbwkDZM7z5w=,tag:FD2cHC3kLUP96S9erJyLOw==,type:str]
    authelia:
        jwt_secret: ENC[AES256_GCM,data:JG+VSlYsX1pRyeURIrUiehntN5bM5/ZbC7RVoimF/NcEF3RsOwDHrV+DA9s=,iv:MvmzU0KXuEf5IyxgXfCqLv5Wk3ZiueSelW0KmR7xAOQ=,tag:mUc7xyCFACb2kdh57P9eEQ==,type:str]
        storage_encryption_key: ENC[AES256_GCM,data:9PJLPwkC15VDY4BR/S+mBl9u/OY1o8cI55+ukXHPUAgSrVNOxxmKWyMUwdg=,iv:um8ekCaK+VeoERXOjxn2kKNCd1DZkwHywUCiaMmJypI=,tag:ldwwn4BcLk5SPGOBTPIUJw==,type:str]
        session_secret: ENC[AES256_GCM,data:QWUn7VNZPxA/njB2HeyVAKTRevWJaBrE/iIqQntfVomFlMuxFpeVgCardjw=,iv:XlYAqa7M3nHpLwNoG2m9SY39xQUn05nWUzDzDsyqNyQ=,tag:wemllBvuuaSEY9DtPXfbPg==,type:str]
sops:
    age:
        - recipient: age1fzrthms7a20xu8s05p8904tneet5xzeh4jkkq724q0mxz9wtau0s3gwfga
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2TkhISFl0RmVTUTBIZWkx
            YU1BUjBWTE1PeTdPSzdrOTI1MnpMcmNqUDMwCm83NVlSMGpRUTdLNFBPajI2WGtD
            ZW1PLzBHSHBtZlFPdVQ4RlZlbTdOeTgKLS0tIDd2MXBvNzFESXZmSmNIUVZQaVVO
            Mm56MHRsaXhqWnJpMDlJRzVWWHZiQjgKHNn8OyuwPxzCRar6cUU0MIAzfsXtcv63
            43/QCltYoFDZqJwJDXhQ2NWk7AOpijNu4wlcbfeLyFCTI6JjSzrdhw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ssppr4cq5dxqa2fyg2d3ke2yud2dgrvv6js50l7ves0hznx353ts4ak02j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqS3ZyRk9ONXY5dHNZSmR4
            OG0rb09CWWhVVUdxZS9vQ2I3TWNpTXkreFNzCnpFZ0pzVmtOdlZURkpvMTJuUFNO
            SzlmcUNzazR6bjdTTEg3d2lyQTNIbmMKLS0tIE5zaGtqR2ZxNHRmNXRMNE51ZVl0
            Y09qSUtZRHludHhGeWh6SnRBMDVieW8KIkcQBFjDWxQiOYPAMa0tKFy2utQyJhIh
            uFKAXIS6C1mF/hXnbaFy8/zKJCoq18M8YGsa8L72ThV+XoDT90umfA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-31T22:15:39Z"
    mac: ENC[AES256_GCM,data:Mxh9gmAKp/QYwrdjgwM8/sFN12SXinZTaVxtAKZUw3FJWMcKlYbgV0NGqxJCrxFe5qBvnMQbJMH2nhwfdT+OKioVAQjir9/101WcABxhh0Vr4RP1AagnSFOZ8G4Pl79uuWkIASHYiOxSD/SxdTe+Rt1AnQSDr+affH6QAFjut7U=,iv:K8lB0NP8jP48X/PCIYIkENk/mF6eUV7yNOYdnKT+r34=,tag:gTspnJnQTJhNAoN4+MBYbw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
