#ENC[AES256_GCM,data:Ce/7ENItZI7fq4jW8DIE9Fh/LpfduvzWnZnGjmGqa8Y/6GuXKu/7l/8=,iv:A7ex1OdpRKpPF+NZ5qiRmO70tFOCZoVvWPcjBWohgro=,tag:cXXPjt3+YglQkt30dbtFQg==,type:comment]
#ENC[AES256_GCM,data:AndO4280CyDTfYHSwP4BTfcyREk=,iv:t0MUsj1ZggTxv7JlOpfq6XHHrqIxQ2IKbNTpdi9e+HE=,tag:4myqowd8H0NmedR/xgfd1A==,type:comment]
#ENC[AES256_GCM,data:iDPtVMdW7MkXMplKIXSXO/CNvD8dLoVq9jyipsG6mrU=,iv:DYq/0D0Kj9TGOgDRti4htyvE8nQaOsaaNzPpdDM5EUQ=,tag:lpqEpmZeuogFMCjq3mk09A==,type:comment]
gpg:
    signing_key_id: ENC[AES256_GCM,data:tn1n6TdySlJFkgT2GKI0KQ==,iv:pyljjVVjT4AFezYbrB5AJzDnlvLp1iaxTExKxenKkKw=,tag:WYzDME8mUT5iwtL/5mhG8Q==,type:str]
    #ENC[AES256_GCM,data:tOKrgbkx45kqNQrNfRMtAtnxwOb+9eO0LFUVCJwI3Gd/jT4J4LTUl5uUOYaCKeXOVt5OyE3970xqDxXixegN,iv:xnD9/zcaCiedH0VpvKK4P2DCQpRIrTLKHfMYmDMVww4=,tag:i9w6oevDrgnkXpSDh5nFcA==,type:comment]
    #ENC[AES256_GCM,data:XGB2xrD8H2JUeW1BvhkekfU2wihzO86CwaqVyhVgCJsw2w0bNlm2/O2m+gOtvA==,iv:y2i1wuqXTzm5Hv2R0SyGjTs3q1KbEVfE3D04Fv/OLcA=,tag:I8to/DgUrFAq7jqu/vdnlw==,type:comment]
    private_key: ENC[AES256_GCM,data:PFmqIYgFjtfS0A03mrUQByl1M3sPcmEGfq7cmLfFHd8=,iv:6bggsaX3JxAVwUNZNXnbl/voHj3BLhCBns3fQf+wKgs=,tag:Uj5cbolSkQ3eqzsVRzUlYg==,type:str]
#ENC[AES256_GCM,data:M30MsdImZfcFNDkLRY5Zgj7HGSH8OwpqH5mCwtQ=,iv:Ca980MV/TkkjQ3hzHo2AAUujwSVMrvGS6/YqO/aS6xs=,tag:b8CHg8Ty4TJQe+6jUnxEDQ==,type:comment]
ssh:
    #ENC[AES256_GCM,data:ON4kp3/t9UiF7d7JrQJ/61FMeQT3HE57vQ==,iv:m0POqFFegVm0tCHyIK/S65YhdThMdviUgroHSGdKZ8A=,tag:iJFzd1UgX8FoRxJDC5EeQg==,type:comment]
    dylbook_ssh_private_key: ENC[AES256_GCM,data:stWDYXryFE8blnmKSjEb/YynHLdA1OfRx7E8IyS4NFnawzY=,iv:nIlvOLoY8mPn5YuM0T0UTtzjuK30T+EyrzuRfswqa7o=,tag:GE4fyrrZdBUqNDSSpJbJ4A==,type:str]
    dylbook_ssh_public_key: ENC[AES256_GCM,data:D10k+nY8tjFWNVZSzXUW6PZcSvPFOJ6VeWh58bpZ9vjqJztwCKpuhMjhGJqSLQbBxFmLTcj2k70fuZWQwxIQ4ypDwiE7Qw3Ma9DHGOaA6YRhAzs2b9/qXy6sXCfvVMar1rwm,iv:PWGSPhTTIIuR6xSuOCzIHnIEJs1pzcE9B22GvVqQ7tA=,tag:wbqB77xlMhP7DUcreWDbJQ==,type:str]
sops:
    age:
        - recipient: age1fzrthms7a20xu8s05p8904tneet5xzeh4jkkq724q0mxz9wtau0s3gwfga
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkSGpnbHY4VDZmRlJsbXJn
            NHdtZ0c1MzM5UWtpb0RCTUpJMXZOL09OU0dzCnl3dVFKaEVHVVlWWmxINkVpOUxP
            a1dSVUxPSXNLbUoxNVhiQ2N5ZmFVMUEKLS0tIE1QbFBCTk5xdlYxM3M3SmkvcTV5
            cHNJM3lhbnZqaTBma01VMHJtV2VkL0UKURztezBQUpj7UnZL9G4Uoar8jTqMsDkL
            Ir/Q9yCc2ZoUPHOkhfCgH3msoeWOfkEwGsERelqETg29D8CjsX2ihQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ssppr4cq5dxqa2fyg2d3ke2yud2dgrvv6js50l7ves0hznx353ts4ak02j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwcVBSeGkyU1VVWUpRdEZm
            MXA2VEo0SitVOFZiYXVqc2ZWME5pLy9VNEU4CndyNEpXRW45SmVtWmFNVnFVeWpK
            UzM2WDlicWFUREhGV1Rpb3FESm5WMWMKLS0tIDFiNlZzY3pFUjBZeCtNekQySnZQ
            MjFrNWZqVjRrSnBiN0M2WUViNldHbjgKrFH0enmVb3oCSvkVHcup/6f9swSdP+/+
            +iFDJZhcai8xSS1IZ6k/JomKw1XThVekMZ7LhxQbDzEsaIZv5hvgXQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-31T22:11:34Z"
    mac: ENC[AES256_GCM,data:z7B5j/HfYZW9AB/9iXncgj+rpuz9aSzbQkY7Mgi5BLbWoVEl8wzJmQarVXNBeY0xOBE31oAM7yVkOM0sMZL5Nd0sfk9AgqHGR8phwJ7IhIIQLgawNswG2Xbsw08fLtbxpbJ9pv7YA7IDHBHkTdQPuTHCJ7UGMJoQpESNgSiXxj4=,iv:7rDMYwIbmhsKZFZzpLWTCIHJ3xSdIz9mrnLKHJtVvqw=,tag:05+nE2BSLZajekiL1UCbCg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
